default: &default
  adapter: postgresql
  pool: 5
  username: 'postgres'
  password: 'paulo0706'
  host: 'localhost' 



development:
  <<: *default
  database: 'Despesas360DB'

test:
  <<: *default
  database: 'despesas360db_test'

production:
  <<: *default
  database: 'despesas360db'